---
# Play 1: ensure Python is present (Ansible needs it)
- name: Bootstrap Python on Amazon Linux
  hosts: web
  gather_facts: false
  become: true
  tasks:
    - name: Install python3 via raw (works even if Python is missing)
      raw: |
        (command -v python3 >/dev/null 2>&1) || (yum -y install python3 || dnf -y install python3)

# Play 2: install Apache and serve Hello, World!
- name: Configure web server
  hosts: web
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure httpd is installed
      package:
        name: httpd
        state: present

    - name: Ensure httpd is enabled and running
      service:
        name: httpd
        state: started
        enabled: true

    - name: Create Hello World page
      copy:
        dest: /var/www/html/index.html
        content: |
          <!doctype html>
          <html><head><title>Hello</title></head>
          <body><h1>Hello, World!</h1><p>Tech Challenge 3 is live.</p></body></html>
        owner: root
        group: root
        mode: "0644"
